# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter:  postgresql
  username: postgres
  host: localhost
  password: secret
  database: my_database_development
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter:  postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

production:
  adapter:  postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
